# Generated by Django 3.2.10 on 2024-03-28 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tag', models.CharField(choices=[('Doces', 'Doces'), ('Caldos', 'Caldos'), ('Americana', 'Americana'), ('Baiana', 'Baiana'), ('Coreana', 'Coreana'), ('Espanhola', 'Espanhola'), ('Francesa', 'Francesa'), ('Italiana', 'Italiana'), ('Japonesa', 'Japonesa'), ('Mexicana', 'Mexicana'), ('Mineira', 'Mineira'), ('Vegetariana', 'Vegetariana'), ('Massas', 'Massas'), ('Molhos', 'Molhos'), ('Salada', 'Salada'), ('Light', 'Light')], default='Doces', max_length=15)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('descricao', models.TextField(max_length=500)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.restaurante')),
            ],
        ),
    ]
