# Generated by Django 3.2.10 on 2024-02-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_alter_prato_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
